#pragma once
#include <vector>
#include <string>
#include <list>
#include <map>
#include <deque>
#include <sstream>
#include <fstream>
#include <ostream>
#include <istream>
#include <iomanip>
#include <algorithm>